# Generated by Django 4.2.15 on 2025-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_onlineclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='class_type',
            field=models.CharField(choices=[('ONLINE', 'Online Class'), ('PRERECORDED', 'Pre-recorded Video')], default='PRERECORDED', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Zoom or Google Meet link for online classes', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='meeting_platform',
            field=models.CharField(blank=True, choices=[('ZOOM', 'Zoom'), ('GOOGLE_MEET', 'Google Meet'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to pre-recorded video content', null=True),
        ),
    ]
