# Generated by Django 4.2.15 on 2025-05-13 12:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_remove_course_student_enrollment_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructions',
            field=tinymce.models.HTMLField(),
        ),
    ]
