# Generated by Django 4.2.15 on 2024-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mode_of_learning',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(default='full name', max_length=255),
            preserve_default=False,
        ),
    ]
