# Generated by Django 4.2.15 on 2025-05-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_teacher_teacherprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(related_name='teacher_groups', to='auth.group'),
        ),
    ]
