# Generated by Django 4.2.15 on 2025-05-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0003_alter_teacher_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_permissions',
            field=models.ManyToManyField(related_name='teacher_permissions', to='auth.permission'),
        ),
    ]
