# Generated by Django 4.2.15 on 2024-09-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='course description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='72 hrs', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructions',
            field=models.TextField(default='course instructions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='content_pdf',
            field=models.FileField(blank=True, null=True, upload_to='topics/pdfs/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('PDF', 'PDF'), ('VIDEO', 'Video')], default='text', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='content_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
