# Generated by Django 4.2.15 on 2024-10-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0002_remove_course_instructions_remove_course_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
    ]
