# Generated by Django 4.2.15 on 2024-09-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0005_alter_quizitemprogress_quiz_item_delete_quizitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
    ]
